@testSOAP_HostAddress = https://localhost:7132

GET {{testSOAP_HostAddress}}/api/weatherforecast

###

GET {{testSOAP_HostAddress}}/api/data/getall

###

@id=12
GET {{testSOAP_HostAddress}}/api/data/appointment/{{id}}

###

GET {{testSOAP_HostAddress}}/api/data/getall

###

GET {{testSOAP_HostAddress}}/api/data/soapnote/{{id}}

###
